package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Announcement")
public class Announcement {
    private String Id;
    private String announcementId;
    private String announcementText;
    private String boardId;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "announcementId-index", attributeName = "announcementId")
    public String getAnnouncementId() {
        return announcementId;
    }

    public void setAnnouncementId(String announcementId) {
        this.announcementId = announcementId;
    }

    @DynamoDBAttribute(attributeName = "AnnouncementText")
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBIgnore
    @Override
    public String toString() {
        return "Announcement{" +
                "Id='" + Id + '\'' +
                ", announcementId='" + announcementId + '\'' +
                ", announcementText='" + announcementText + '\'' +
                ", boardId='" + boardId + '\'' +
                '}';
    }
}
