package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Board")
public class Board {
    private String Id;
    private String boardId;
    private String postDate;
    private String courseId;

    public Board() {
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "boardId-index", attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }


    @DynamoDBAttribute(attributeName = "postDate")
    public String getPostDate() {
        return postDate;
    }

    public void setPostDate(String postDate) {
        this.postDate = postDate;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBIgnore
    @Override
    public String toString() {
        return "Board{" +
                "Id='" + Id + '\'' +
                ", boardId='" + boardId + '\'' +
                ", postDate='" + postDate + '\'' +
                ", courseId='" + courseId + '\'' +
                '}';
    }
}
