package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Set;

@DynamoDBTable(tableName = "Course")
public class Course {
    private String Id;
    private String courseId;
    private String courseName;
    private String professorId;
    private String taId;
    private String department;
    private Set<String> roster;

    public Course() {
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "courseId-index", attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "courseName")
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName = "taId")
    public String getTaId() {
        return taId;
    }

    public void setTaId(String taId) {
        this.taId = taId;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "roster")
    public Set<String> getRoster() {
        return roster;
    }

    public void setRoster(Set<String> roster) {
        this.roster = roster;
    }

    @DynamoDBIgnore
    @Override
    public String toString() {
        return "Course{" +
                "Id='" + Id + '\'' +
                ", courseId='" + courseId + '\'' +
                ", courseName='" + courseName + '\'' +
                ", professorId='" + professorId + '\'' +
                ", taId='" + taId + '\'' +
                ", department='" + department + '\'' +
                ", roster=" + roster +
                '}';
    }

}
