package com.csye6225.spring2020.courseservice.datamodel;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndex;

@DynamoDBTable(tableName = "Course")
public class Course {
    private String courseId;
    private String courseName;
    private String professorId;
    private String taId;
    private String department;
    private String programId;

    public Course() {
    }

    @DynamoDBHashKey(attributeName = "courseId")
    @DynamoDBAutoGeneratedKey
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "courseName")
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName = "taId")
    public String getTaId() {
        return taId;
    }

    public void setTaId(String taId) {
        this.taId = taId;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartmentId(String department) {
        this.department = department;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "programId", attributeName = "programId")
    public String getProgramId() {
        return programId;
    }

    public void setProgramId(String programId) {
        this.programId = programId;
    }

    @Override
    public String toString() {
        return "Course [courseId=" + courseId + ", courseName=" + courseName + ", professorId=" + professorId
                + ", taId=" + taId + ", department=" + department + ", programId=" + programId + "]";
    }


}
