package com.csye6225.spring2020.courseservice.datamodel;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndex;

@DynamoDBTable(tableName = "Course")
public class Course {
	private String courseId;
	private String courseName;
	private String professorId;
	private String taId;
	private String department;
	private String programId;
	private String boardId;
	private Set<String> roster;
	private String notificationTopic;

	public Course() {
	}

	@DynamoDBHashKey(attributeName = "courseId")
	@DynamoDBAutoGeneratedKey
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBAttribute(attributeName = "courseName")
	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@DynamoDBAttribute(attributeName = "professorId")
	public String getProfessorId() {
		return professorId;
	}

	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}

	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}

	public void setTaId(String taId) {
		this.taId = taId;
	}

	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "programId-index", attributeName = "programId")
	public String getProgramId() {
		return programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "roster")
	public Set<String> getRoster() {
		return roster;
	}

	public void setRoster(Set<String> roster) {
		this.roster = roster;
	}

	@DynamoDBAttribute(attributeName = "notificationTopic")
	public String getNotificationTopic() {
		return notificationTopic;
	}

	public void setNotificationTopic(String notificationTopic) {
		this.notificationTopic = notificationTopic;
	}

}
