package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Lecture")
public class Lecture {
    private String lectureId;
    private String notes;
    private String material;
    private String courseId;

    public Lecture() {
    }

    @DynamoDBHashKey(attributeName = "lectureId")
    @DynamoDBAutoGeneratedKey
    public String getLectureId() {
        return lectureId;
    }

    public void setLectureId(String lectureId) {
        this.lectureId = lectureId;
    }

    @DynamoDBAttribute(attributeName = "notes")
    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @DynamoDBAttribute(attributeName = "material")
    public String getMaterial() {
        return material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "courseId", attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @Override
    public String toString() {
        return "Lecture [lectureId=" + lectureId + ", notes=" + notes + ", material=" + material + ", courseId="
                + courseId + "]";
    }

}
