package com.csye6225.spring2020.courseservice.datamodel;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Program")
public class Program {
    private String programId;
    private String programName;
    private String department;

    public Program() {
    }

    @DynamoDBHashKey(attributeName = "programId")
    @DynamoDBAutoGeneratedKey
    public String getProgramId() {
        return programId;
    }

    public void setProgramId(String programId) {
        this.programId = programId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "department-index", attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "programName")
    public String getProgramName() {
        return programName;
    }

    public void setProgramName(String programName) {
        this.programName = programName;
    }

    @Override
    public String toString() {
        return "Program [programId=" + programId + ", programName=" + programName + ", department=" + department
                + "]";
    }


}
