package com.csye6225.spring2020.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "registrar")
public class Registrar {
	private String registrationId;
	private String offeringId;
	private String offeringType;
	private String department;
	private Integer perUnitPrice;

	public Registrar() {

	}

	@DynamoDBHashKey(attributeName = "registrationId")
	@DynamoDBAutoGeneratedKey
	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String RegistrationId) {
		this.registrationId = RegistrationId;
	}

	@DynamoDBAttribute(attributeName = "offeringId")
	public String getOfferingId() {
		return offeringId;
	}

	public void setOfferingId(String offeringId) {
		this.offeringId = offeringId;
	}

	@DynamoDBAttribute(attributeName = "offeringType")
	public String getOfferingType() {
		return offeringType;
	}

	public void setOfferingType(String offeringType) {
		this.offeringType = offeringType;
	}

	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "perUnitPrice")
	public Integer getPerUnitPrice() {
		return perUnitPrice;
	}

	public void setPerUnitPrice(Integer perUnitPrice) {
		this.perUnitPrice = perUnitPrice;
	}

}